config/routes.rb
Zombies::Application.routes.draw do
  resources :items  do
    member do
      get :show
      patch :pickup
      patch :use
    end
  end

  resources :zombie_masters do
    resources :floor_plans, module: 'zombie_masters' do
      resources :tags, module: 'floor_plans' do
        member do
          get :assign
        end
      end
    end
    member do
      get :assume
    end
  end

  resources :players do 
    collection do
      get "tick"
      get "infectshow"
      post "infect"
    end
    member do
      get 'assume'
      get 'arrive_at_base'
    end
  end

  resources :commanders do
    member do
      get :assume
      post :message
      post :broadcast
    end
  end

  resources :base do
    member do
      get :index
      post :items
    end
  end

  get 'dash' => 'player_dashboard#index'

  root 'application#index'

  post 'api/bluetooth/:id' => 'api#bluetooth'
  get 'api/bluetooth/:id' => 'api#bluetooth'
  post 'api/tag/:id' => 'api#tag'
  get 'api/tag/:id' => 'api#tag'
  get 'api/base' => 'api#base'

  

end

app/models/floor_plan.rb
class FloorPlan < ActiveRecord::Base
  self.table_name = 'floorplans'
  image_accessor :image
  validates :name, :image, presence: true 
  has_many :tags, foreign_key: 'floorplan_id'
end

app/models/zombie_master.rb
class ZombieMaster < Player
end

app/controllers/zombie_masters/floor_plans/tags_controller.rb
module ZombieMasters
  module FloorPlans
    class TagsController < ApplicationController

      before_filter :load_floor_plan

      def new
        @tag = Tag.new(tag_params)
        if @tag.save
          redirect_to zombie_master_floor_plan_path(:current, @floor_plan), notice: 'Tag created'
        else
          redirect_to zombie_master_floor_plan_path(:current, @floor_plan), alert: 'Problem creating tag'
        end
      end

      def show
        @tag = Tag.find(params[:id])
      end

      def destroy
        tag = Tag.find(params[:id])
        tag.destroy
        redirect_to zombie_master_floor_plan_path(:current, @floor_plan), notice: 'Tag removed'
      end

      def update
        @tag = Tag.find(params[:id])
        @tag.ref = params[:tag][:ref]
        if @tag.save
          flash.now[:notice] = 'Updated'
        else 
          flash.now[:alert] = 'Problem'
        end
        render action: :show
      end

      def assign
        @tag = Tag.find(params[:id])
        @tag.item.destroy if @tag.item
        item = eval(params[:type]).new
        item.tag = @tag
        if item.save
          flash.now[:notice] = 'Updated'
        else 
          flash.now[:alert] = 'Problem'
        end
        render action: :show
      end

      private

      def tag_params
        params[:tag] = {}
        params[:tag][:x] = params[:x]
        params[:tag][:y] = params[:y]
        params[:tag][:floorplan_id] = @floor_plan.id
        params.require(:tag).permit(:x, :y, :floorplan_id)
      end

      def load_floor_plan
        @floor_plan = FloorPlan.find(params[:floor_plan_id])
      end

    end
  end
end

app/controllers/zombie_masters/floor_plans_controller.rb
module ZombieMasters
  class FloorPlansController < ApplicationController
    def new
      @floor_plan = FloorPlan.new
    end

    def create
      @floor_plan = FloorPlan.new(floor_plan_params)
      if @floor_plan.save
        redirect_to zombie_master_floor_plan_path(:current, @floor_plan)
      else
        render :new
      end
    end

    def show
      @floor_plan = FloorPlan.find(params[:id])
      @tags = @floor_plan.tags
    end

    def destroy
      @floor_plan = FloorPlan.find(params[:id])
      @floor_plan.destroy
      redirect_to zombie_master_path(:current)
    end
    
    private

    def floor_plan_params
      params.require(:floor_plan).permit(:image, :name)
    end
  end
end

app/controllers/zombie_masters/tags_controller.rb
module ZombieMasters
  class TagsController < ApplicationController
    include ZombieMasterHelper 

    def new
      @tag = Tag.new
    end

    def create 
      @tag = Tag.new(tag_params)
      if @tag.save
        redirect_to zombie_master_tags_path(:current)
      else
        redirect_to zombie_master_floor_plan_path(params[:floor_plan])
      end
    end

    def edit
    end

    def update
    end

    def destroy
    end

    private

    def tag_params
      params.require(:tag)
    end
  end
end

app/controllers/zombie_masters_controller.rb
class ZombieMastersController < ApplicationController
  include ZombieMasterHelper

  before_filter :load_zombie_master, only: :show

  def new
    @zombie_master = ZombieMaster.new
  end

  def create
    @zombie_master = ZombieMaster.new(zombie_master_params)
    if @zombie_master.save
      session[:player_id] = @zombie_master.id
      redirect_to @zombie_master
    else
      render :new
    end
  end

  def show
    @floor_plans = FloorPlan.all
  end

  def assume
    zombie_master = ZombieMaster.find(params[:id])
    session[:player_id] = zombie_master.id
    redirect_to zombie_master
  end

  private

  def zombie_master_params
    params.require(:zombie_master).permit(:name, :phone)
  end
end

app/helpers/zombie_master_helper.rb
module ZombieMasterHelper
  def load_zombie_master
    @zombie_master = ZombieMaster.find(session[:player_id])
  end
end

app/views/zombie_masters/floor_plans/_players.html.slim
- players = Player.where(x: x.to_s, y: y.to_s, floorplan_id: floorplan_id.to_i)
- players.each do |player| 
  i.icon-group title = player.name

app/views/zombie_masters/floor_plans/new.html.slim
h1 New floor plan

= form_for @floor_plan, url: zombie_master_floor_plans_path(:current) do |f|
  - if f.object.errors.any?
    .alert.alert-danger
      - f.object.errors.full_messages.each do |message|
        p
          = message

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :image
    = f.file_field :image, class: 'form-control'

  .form-control
    = f.submit

app/views/zombie_masters/floor_plans/show.html.slim
h1 Floor Plan
h2 = @floor_plan.name

- if flash[:notice]
  .alert.alert-success
    = flash[:notice]
- if flash[:alert]
  .alert.alert-danger
    = flash[:alert]

table.floor-plan style = "background-image: url(#{@floor_plan.image.thumb('1170x').url});"
  - 50.times do |y_count|
    tr
      - 50.times do |x_count|
        - tag = @tags.select{|t| t.x == x_count && t.y == y_count }.first
        - if tag
          - if tag.item
            td.tagged onclick = "window.location = '/zombie_masters/current/floor_plans/#{@floor_plan.id}/tags/#{tag.id}'; return false;" style = "color: #{tag.item.colour};"
              i.icon-circle
              = render 'players', x: x_count, y: y_count, floorplan_id: @floor_plan.id
          - else 
            td.tagged (onclick = "window.location = '/zombie_masters/current/floor_plans/#{@floor_plan.id}/tags/#{tag.id}'; return false;")
              i.icon-circle
              = render 'players', x: x_count, y: y_count, floorplan_id: @floor_plan.id
        - else
          td (onclick = "window.location = '/zombie_masters/current/floor_plans/#{@floor_plan.id}/tags/new?x=#{x_count}&y=#{y_count}'; return false;") 
            | &nbsp;
            = render 'players', x: x_count, y: y_count, floorplan_id: @floor_plan.id