config/routes.rb
Zombies::Application.routes.draw do
  resources :items  do
    member do
      get :show
      patch :pickup
      patch :use
    end
  end

  resources :zombie_masters do
    resources :floor_plans, module: 'zombie_masters' do
      resources :tags, module: 'floor_plans' do
        member do
          get :assign
        end
      end
    end
    member do
      get :assume
    end
  end

  resources :players do 
    collection do
      get "tick"
      get "infectshow"
      post "infect"
    end
    member do
      get 'assume'
      get 'arrive_at_base'
    end
  end

  resources :commanders do
    member do
      get :assume
      post :message
      post :broadcast
    end
  end

  resources :base do
    member do
      get :index
      post :items
    end
  end

  get 'dash' => 'player_dashboard#index'

  root 'application#index'

  post 'api/bluetooth/:id' => 'api#bluetooth'
  get 'api/bluetooth/:id' => 'api#bluetooth'
  post 'api/tag/:id' => 'api#tag'
  get 'api/tag/:id' => 'api#tag'
  get 'api/base' => 'api#base'

  

end

app/models/commander.rb
class Commander < Player
end

app/controllers/commanders_controller.rb
class CommandersController < ApplicationController
  include CommanderHelper

  before_filter :load_commander, only: [:show, :message, :broadcast]

  def new
    @commander = Commander.new
  end

  def create
    @commander = Commander.new(commander_params)
    if @commander.save
      session[:player_id] = @commander.id
      redirect_to @commander
    else
      render action: :new
    end
  end

  def show
    @players = Player.where(type: nil)
  end

  def message
    @player = Player.find(params[:player_id])
    @messenger = Messenger.new
    if @messenger.message(@player.phone, params[:message])
      redirect_to @commander, notice: 'Message sent'
    else 
      redirect_to @commander, notice: @messenger.error
    end
  end

  def broadcast
    @messenger = Messenger.new
    Player.human.each do |player|
      @messenger.message(player.phone, params[:message])
    end
    redirect_to @commander, notice: 'Message broadcast'
  end

  def assume
    commander = Commander.find(params[:id])
    session[:player_id] = commander.id
    redirect_to commander
  end

  private

  def commander_params
    params.require(:commander).permit(:name, :phone)
  end
end

app/helpers/commander_helper.rb
module CommanderHelper
  def load_commander
    @commander = Commander.find(session[:player_id])
  end
end

app/views/commanders/new.html.slim
h1 New Commander

= form_for @commander do |f|
  - if f.object.errors.any?
    .alert.alert-danger
      - f.object.errors.full_messages.each do |message|
        p
          = message

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :phone
    = f.text_field :phone, class: 'form-control'

  .form-group
    = f.submit

app/views/commanders/show.html.slim
h1 Commander: #{@commander.name}

h2 Players

- if flash[:notice]
  .alert = flash[:notice]

= form_tag broadcast_commander_path(:current) do
  .input-append
    = text_field_tag :message
    = submit_tag 'Broadcast to all players', class: 'btn btn-success'
p

table.table
  tr
    th Name
    th Options
  - @players.each do |player|
    tr
      td
        = player.name
      td 
        = form_tag message_commander_path(:current) do
          .input-append
            = text_field_tag :message
            = hidden_field_tag :player_id, player.id
            = submit_tag 'Message', class: 'btn btn-success'